
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectocompi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TypeInteger = 32;
  public static final int End = 7;
  public static final int Coma = 6;
  public static final int If = 15;
  public static final int Id = 36;
  public static final int Sub = 28;
  public static final int Else = 17;
  public static final int Read = 9;
  public static final int MultDiv = 11;
  public static final int Error = 38;
  public static final int Then = 16;
  public static final int TypeBoolean = 31;
  public static final int Parizq = 4;
  public static final int While = 24;
  public static final int To = 20;
  public static final int Ampersand = 14;
  public static final int For = 19;
  public static final int EOF = 0;
  public static final int Step = 22;
  public static final int Function = 27;
  public static final int error = 1;
  public static final int Module = 30;
  public static final int As = 35;
  public static final int Do = 23;
  public static final int Num = 2;
  public static final int ElseIf = 18;
  public static final int SumaResta = 10;
  public static final int Dim = 34;
  public static final int TypeString = 33;
  public static final int OpRel = 13;
  public static final int Parder = 5;
  public static final int ContString = 37;
  public static final int Structure = 29;
  public static final int ByVal = 26;
  public static final int Write = 8;
  public static final int Next = 21;
  public static final int Loop = 25;
  public static final int Igual = 12;
  public static final int Newline = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Num",
  "Newline",
  "Parizq",
  "Parder",
  "Coma",
  "End",
  "Write",
  "Read",
  "SumaResta",
  "MultDiv",
  "Igual",
  "OpRel",
  "Ampersand",
  "If",
  "Then",
  "Else",
  "ElseIf",
  "For",
  "To",
  "Next",
  "Step",
  "Do",
  "While",
  "Loop",
  "ByVal",
  "Function",
  "Sub",
  "Structure",
  "Module",
  "TypeBoolean",
  "TypeInteger",
  "TypeString",
  "Dim",
  "As",
  "Id",
  "ContString",
  "Error"
  };
}

